from ..tools.registry import get_tool_registry

class ExecutorAgent:
    def __init__(self):
        self.tools = get_tool_registry()

    def execute_plan(self, plan: list):
        """
        Executes a list of steps generated by the Planner.
        Returns a dictionary of results keyed by tool name (or step index/description).
        """
        results = {}
        
        if not isinstance(plan, list):
             return {"error": "Invalid plan format. Expected a list of steps."}

        for i, step in enumerate(plan):
            tool_name = step.get("tool_name")
            arguments = step.get("arguments", {})
            
            if tool_name in self.tools:
                tool_func = self.tools[tool_name]
                try:
                    # Execute the tool
                    print(f"Executing step {i+1}: {tool_name} with {arguments}")
                    execution_result = tool_func(**arguments)
                    results[f"step_{i+1}_{tool_name}"] = execution_result
                except Exception as e:
                    results[f"step_{i+1}_{tool_name}"] = {"error": str(e)}
            else:
                results[f"step_{i+1}_{tool_name}"] = {"error": f"Tool '{tool_name}' not found."}
        
        return results
